// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';
import {main} from '../models';

export function AddTagToConversation(arg1:number,arg2:string):Promise<void>;

export function ArchiveConversation(arg1:number):Promise<void>;

export function CancelGoogleSheetsAuth(arg1:number):Promise<void>;

export function CancelGoogleSheetsAuthTemp(arg1:string):Promise<void>;

export function CancelProcessing(arg1:number):Promise<void>;

export function CheckForUpdate():Promise<services.UpdateInfo>;

export function ClearConversationMessages(arg1:number):Promise<void>;

export function ClearLog():Promise<void>;

export function CreateAndSwitchToNewDatabase(arg1:string):Promise<void>;

export function CreateConversation(arg1:string,arg2:any,arg3:any):Promise<models.Conversation>;

export function CreateDataSource(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string):Promise<void>;

export function CreateLLMProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function CreateSkill(arg1:string,arg2:string):Promise<models.Skill>;

export function DeleteConversation(arg1:number):Promise<void>;

export function DeleteDataSource(arg1:number):Promise<void>;

export function DeleteLLMProvider(arg1:number):Promise<void>;

export function DeleteSkill(arg1:number):Promise<void>;

export function DetectModelMaxTokens(arg1:number):Promise<number>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<void>;

export function DuplicateConversation(arg1:number):Promise<models.Conversation>;

export function ExecuteQuery(arg1:number,arg2:string):Promise<main.QueryResult>;

export function ExportConversationHTML(arg1:number):Promise<string>;

export function ExportConversationMarkdown(arg1:number):Promise<string>;

export function ExportConversationPDF():Promise<void>;

export function ExportDatabase(arg1:string,arg2:Array<string>,arg3:boolean):Promise<string>;

export function ExportLog():Promise<string>;

export function GetActiveDatabaseInfo():Promise<services.ActiveDatabaseInfo>;

export function GetAgentLoopConfig():Promise<main.AgentLoopConfigJSON>;

export function GetAppSetting(arg1:string):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetConversationMessages(arg1:number):Promise<Array<models.ConversationMessage>>;

export function GetConversationSkillIDs(arg1:number):Promise<Array<number>>;

export function GetDiscussionDefaults():Promise<models.DiscussionDefaults>;

export function GetGeneralSettings():Promise<main.GeneralSettings>;

export function GetLoggingEnabled():Promise<boolean>;

export function GetSchemaPreview(arg1:number):Promise<main.SchemaPreview>;

export function GetSupportedDBTypes():Promise<Array<services.DBTypeInfo>>;

export function GetTagsForConversation(arg1:number):Promise<Array<string>>;

export function ListAllTags():Promise<Array<string>>;

export function ListConversations():Promise<Array<models.Conversation>>;

export function ListDataSources():Promise<Array<main.DataSourceSetting>>;

export function ListDiscussions():Promise<Array<string>>;

export function ListLLMProviders():Promise<Array<main.LLMProviderSetting>>;

export function ListSkills():Promise<Array<models.Skill>>;

export function MigrateGoogleAuthConfig(arg1:string,arg2:number):Promise<void>;

export function PerformUpgradeRestart():Promise<void>;

export function PickExistingDatabaseFile():Promise<string>;

export function PickNewDatabaseLocation():Promise<string>;

export function ProcessUserMessage(arg1:number,arg2:string):Promise<void>;

export function RemoveTagFromConversation(arg1:number,arg2:string):Promise<void>;

export function ResetAgentLoopConfigKey(arg1:string):Promise<void>;

export function ResetAllAgentLoopConfig():Promise<void>;

export function ResetToDefaultDatabase():Promise<void>;

export function RestoreConversation(arg1:number):Promise<void>;

export function RevokeGoogleSheetsAuth(arg1:number):Promise<void>;

export function SetAgentLoopConfigKey(arg1:string,arg2:string):Promise<void>;

export function SetAppSetting(arg1:string,arg2:string):Promise<void>;

export function SetConversationSkill(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetDefaultDataSource(arg1:number):Promise<void>;

export function SetDefaultLLMProvider(arg1:number):Promise<void>;

export function SetLoggingEnabled(arg1:boolean):Promise<void>;

export function SetSkillActive(arg1:number,arg2:boolean):Promise<void>;

export function StartGoogleSheetsAuth(arg1:number):Promise<Record<string, any>>;

export function StartGoogleSheetsAuthTemp(arg1:string):Promise<Record<string, any>>;

export function SwitchToExistingDatabase(arg1:string):Promise<void>;

export function TestDataSource(arg1:number):Promise<string>;

export function TestLLMProviderConnection(arg1:number):Promise<string>;

export function TestNewDataSource(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string):Promise<string>;

export function UpdateConversationContextDetails(arg1:number,arg2:boolean):Promise<void>;

export function UpdateConversationMaxContextMessages(arg1:number,arg2:number):Promise<void>;

export function UpdateConversationMaxMessages(arg1:number,arg2:number):Promise<void>;

export function UpdateConversationPinned(arg1:number,arg2:boolean):Promise<void>;

export function UpdateConversationSettings(arg1:number,arg2:any,arg3:any):Promise<void>;

export function UpdateConversationStreamingEnabled(arg1:number,arg2:boolean):Promise<void>;

export function UpdateConversationSummarize(arg1:number,arg2:boolean):Promise<void>;

export function UpdateConversationTechDetails(arg1:number,arg2:boolean):Promise<void>;

export function UpdateConversationTitle(arg1:number,arg2:string):Promise<models.Conversation>;

export function UpdateConversationVizEnabled(arg1:number,arg2:boolean):Promise<void>;

export function UpdateDataSource(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:number,arg11:string,arg12:string):Promise<void>;

export function UpdateDiscussionDefaults(arg1:models.DiscussionDefaults):Promise<void>;

export function UpdateGeneralSettings(arg1:main.GeneralSettings):Promise<void>;

export function UpdateLLMProvider(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function UpdateSkill(arg1:number,arg2:string,arg3:string):Promise<models.Skill>;
