// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveConversation(arg1) {
  return window['go']['main']['App']['ArchiveConversation'](arg1);
}

export function ClearConversationMessages(arg1) {
  return window['go']['main']['App']['ClearConversationMessages'](arg1);
}

export function CreateConversation(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateConversation'](arg1, arg2, arg3);
}

export function CreateDataSource(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['CreateDataSource'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function CreateLLMProvider(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateLLMProvider'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteDataSource(arg1) {
  return window['go']['main']['App']['DeleteDataSource'](arg1);
}

export function DeleteLLMProvider(arg1) {
  return window['go']['main']['App']['DeleteLLMProvider'](arg1);
}

export function DuplicateConversation(arg1) {
  return window['go']['main']['App']['DuplicateConversation'](arg1);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2);
}

export function GetConversationMessages(arg1) {
  return window['go']['main']['App']['GetConversationMessages'](arg1);
}

export function GetGeneralSettings() {
  return window['go']['main']['App']['GetGeneralSettings']();
}

export function GetSchemaPreview(arg1) {
  return window['go']['main']['App']['GetSchemaPreview'](arg1);
}

export function GetSupportedDBTypes() {
  return window['go']['main']['App']['GetSupportedDBTypes']();
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListDataSources() {
  return window['go']['main']['App']['ListDataSources']();
}

export function ListDiscussions() {
  return window['go']['main']['App']['ListDiscussions']();
}

export function ListLLMProviders() {
  return window['go']['main']['App']['ListLLMProviders']();
}

export function ProcessUserMessage(arg1, arg2) {
  return window['go']['main']['App']['ProcessUserMessage'](arg1, arg2);
}

export function RestoreConversation(arg1) {
  return window['go']['main']['App']['RestoreConversation'](arg1);
}

export function SetDefaultDataSource(arg1) {
  return window['go']['main']['App']['SetDefaultDataSource'](arg1);
}

export function SetDefaultLLMProvider(arg1) {
  return window['go']['main']['App']['SetDefaultLLMProvider'](arg1);
}

export function TestDataSource(arg1) {
  return window['go']['main']['App']['TestDataSource'](arg1);
}

export function TestLLMProviderConnection(arg1) {
  return window['go']['main']['App']['TestLLMProviderConnection'](arg1);
}

export function TestNewDataSource(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['TestNewDataSource'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateConversationContextDetails(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationContextDetails'](arg1, arg2);
}

export function UpdateConversationMaxContextMessages(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationMaxContextMessages'](arg1, arg2);
}

export function UpdateConversationMaxMessages(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationMaxMessages'](arg1, arg2);
}

export function UpdateConversationPinned(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationPinned'](arg1, arg2);
}

export function UpdateConversationSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConversationSettings'](arg1, arg2, arg3);
}

export function UpdateConversationSummarize(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationSummarize'](arg1, arg2);
}

export function UpdateConversationTechDetails(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationTechDetails'](arg1, arg2);
}

export function UpdateConversationTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationTitle'](arg1, arg2);
}

export function UpdateDataSource(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['UpdateDataSource'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function UpdateGeneralSettings(arg1) {
  return window['go']['main']['App']['UpdateGeneralSettings'](arg1);
}

export function UpdateLLMProvider(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateLLMProvider'](arg1, arg2, arg3, arg4, arg5);
}
