// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {services} from '../models';

export function ArchiveConversation(arg1:number):Promise<void>;

export function ClearConversationMessages(arg1:number):Promise<void>;

export function CreateConversation(arg1:string,arg2:any,arg3:any):Promise<models.Conversation>;

export function CreateDataSource(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string):Promise<void>;

export function CreateLLMProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CreateSkill(arg1:string,arg2:string):Promise<models.Skill>;

export function DeleteConversation(arg1:number):Promise<void>;

export function DeleteDataSource(arg1:number):Promise<void>;

export function DeleteLLMProvider(arg1:number):Promise<void>;

export function DeleteSkill(arg1:number):Promise<void>;

export function DuplicateConversation(arg1:number):Promise<models.Conversation>;

export function ExecuteQuery(arg1:number,arg2:string):Promise<main.QueryResult>;

export function GetConversationMessages(arg1:number):Promise<Array<models.ConversationMessage>>;

export function GetConversationSkillIDs(arg1:number):Promise<Array<number>>;

export function GetGeneralSettings():Promise<main.GeneralSettings>;

export function GetSchemaPreview(arg1:number):Promise<main.SchemaPreview>;

export function GetSupportedDBTypes():Promise<Array<services.DBTypeInfo>>;

export function ListConversations():Promise<Array<models.Conversation>>;

export function ListDataSources():Promise<Array<main.DataSourceSetting>>;

export function ListDiscussions():Promise<Array<string>>;

export function ListLLMProviders():Promise<Array<main.LLMProviderSetting>>;

export function ListSkills():Promise<Array<models.Skill>>;

export function ProcessUserMessage(arg1:number,arg2:string):Promise<void>;

export function RestoreConversation(arg1:number):Promise<void>;

export function SetConversationSkill(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetDefaultDataSource(arg1:number):Promise<void>;

export function SetDefaultLLMProvider(arg1:number):Promise<void>;

export function SetSkillActive(arg1:number,arg2:boolean):Promise<void>;

export function TestDataSource(arg1:number):Promise<string>;

export function TestLLMProviderConnection(arg1:number):Promise<string>;

export function TestNewDataSource(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string):Promise<string>;

export function UpdateConversationContextDetails(arg1:number,arg2:boolean):Promise<void>;

export function UpdateConversationMaxContextMessages(arg1:number,arg2:number):Promise<void>;

export function UpdateConversationMaxMessages(arg1:number,arg2:number):Promise<void>;

export function UpdateConversationPinned(arg1:number,arg2:boolean):Promise<void>;

export function UpdateConversationSettings(arg1:number,arg2:any,arg3:any):Promise<void>;

export function UpdateConversationSummarize(arg1:number,arg2:boolean):Promise<void>;

export function UpdateConversationTechDetails(arg1:number,arg2:boolean):Promise<void>;

export function UpdateConversationTitle(arg1:number,arg2:string):Promise<models.Conversation>;

export function UpdateConversationVizEnabled(arg1:number,arg2:boolean):Promise<void>;

export function UpdateDataSource(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:number,arg11:string,arg12:string):Promise<void>;

export function UpdateGeneralSettings(arg1:main.GeneralSettings):Promise<void>;

export function UpdateLLMProvider(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateSkill(arg1:number,arg2:string,arg3:string):Promise<models.Skill>;
